#!/bin/sh -eu

# heavy inspiration from https://github.com/cgsdev0/advent-of-code/tree/main/2024/day1

mkfifo left right

awk '{print $1}' input |
  sort -n >left &

awk '{print $2}' input |
  sort -n >right &

paste -d'-' left right |
  bc |
  tr -d '-' |
  paste -sd+ - |
  bc # 3508942

rm left right
